-- Table for submissions from the public forms.
-- The backend inserts and reads these rows through the service role key.

create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  submission_type text not null,
  name text,
  title text,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by text
);

alter table public.form_submissions enable row level security;

create index if not exists form_submissions_created_at_idx
  on public.form_submissions (created_at desc);