-- Admin access list for the admin portal.
-- The first authenticated user auto-bootstraps as owner via backend/api/users.js.

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  display_name text,
  role text not null default 'editor',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create index if not exists admin_users_email_idx
  on public.admin_users (email);
